name: CI/CD Pipeline

on:
  push:
    branches: [main]
    paths:
      - 'bikesafe_app/**'
      - '.github/workflows/ci-cd.yml'
  pull_request:
    branches: [main]
    paths:
      - 'bikesafe_app/**'
      - '.github/workflows/ci-cd.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.27.1'

      # 3. Install Flutter dependencies
      - name: Install Flutter dependencies
        run: flutter pub get
        working-directory: bikesafe_app

      # 4. Create .env fisle from secret
      - name: Create .env file
        working-directory: bikesafe_app
        run: |
          echo "${{ secrets.ENV_FILE }}" | base64 -d > assets/.env

      # 5. Create google-services.json from secrets
      - name: Create google-services.json
        working-directory: bikesafe_app
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 -d > android/app/google-services.json
      - name: Create Release Keystore
        working-directory: bikesafe_app  
        run: echo "${{ secrets.MY_RELEASE_KEY_B64 }}" | base64 -d > android/app/my-release-key.jks    
      - name: Create local.properties file
        working-directory: bikesafe_app/android
        run: |
          echo "${{ secrets.LOCAL_PROPERTIES }}" | base64 -d > local.properties
        
      - name: Create client secret JSON file
        working-directory: bikesafe_app/android/app
        run: |
          echo "${{ secrets.CLIENT_SECRET_JSON }}" | base64 -d > client_secret_1087501086163-ut0hsbk8oabd22tk8u6nh442pcvrsiju.apps.googleusercontent.com.json
        
      - name: Create strings.xml file
        working-directory: bikesafe_app/android/app/src/main/res/values
        run: |
          echo "${{ secrets.STRINGS_XML }}" | base64 -d > strings.xml   
      # (Optional) Debug print – use caution with secrets
      - name: Debug .env content
        working-directory: bikesafe_app
        run: |
          echo "== Contents of .env =="
          cat assets/.env

      - name: Debug google-services.json content
        working-directory: bikesafe_app
        run: |
          echo "== Contents of google-services.json =="
          cat android/app/google-services.json

      # 6. Build the release APK
      - name: Build Flutter APK (Release)
        run: flutter build apk --release --dart-define=PRODUCTION=true
        working-directory: bikesafe_app

      # 7. Upload the APK artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-apk
          path: bikesafe_app/build/app/outputs/flutter-apk/app-release.apk