name: CI Pipeline

on:
  push:
    branches:
      - main    # Trigger on push to main branch for development

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.3.0'  # Specify the Flutter version

    - name: Install dependencies for frontend
      run: bash scripts/setup-dev.sh  # Run the setup script for frontend

  deploy-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Specify the Node.js version

    - name: Install dependencies for backend
      run: bash scripts/setup-dev.sh  # Run the setup script for backend